version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
     - ./db.env

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    env_file:
     - ./app.env
    volumes:
      - ./data/nextcloud:/var/www/html
    restart: always

networks:
  default:
    external:
      name: nginx-proxy